version: '3'
services: 
  web:
    container_name: php-apache
    build :
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes: 
      - ./:/var/www/html
    ports:
     - 8080:80
    networks:
     - lamp_docker

  db:
    image: mysql:latest
    container_name: db
    # command: --default-authentication-plugin=mysql_native_password
    # restart: always
    environment:
      MYSQL_USER: lamp_docker
      MYSQL_DATABASE: login_procedural_users
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD : 1
    #  MYSQL_ROOT_PASSWORD: 
    #  MYSQL_RANDOM_ROOT_PASSWORD: 
    volumes:
     - ./dbdata:/docker-entrypoint-initdb.d
    ports:
      - 9906:3306
    networks:
     - lamp_docker

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
     - 8081:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db
    networks:
     - lamp_docker

networks:
  lamp_docker:
    driver: bridge
  
